name: Semgrep security check

description: Analyzes the codebase for security vulnerabilities and issues using Semgrep

inputs:
  SEMGREP_PUBLISH_TOKEN:
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Semgrep
      id: semgrep
      uses: semgrep/semgrep-action@v1
      with:
        publishToken: ${{ inputs.SEMGREP_PUBLISH_TOKEN }}