name: Get called workflow ref

description: >
  A workaround to the issue: https://github.com/actions/toolkit/issues/1264.
  
  This is needed for the reusable workflow to be able to access its own version (commit hash)
  that is being called by the caller workflow. This allows for using a proper ref of composite actions
  inside the reusable workflow.

inputs:
  GH_TOKEN_ADMIN:
    required: true
  
outputs:
  caller-ref:
    value: ${{ steps.workflows-ref.outputs.caller-ref }}

runs:
  using: composite
  steps:
    - name: Get workflow reference
      id: workflows-ref
      shell: bash
      run: |
        ref=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ inputs.GH_TOKEN_ADMIN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/splunk/splunk-add-on-for-microsoft-cloud-services/actions/runs/${{ github.run_id }} | jq -r '.referenced_workflows[0] | .ref')
        echo "caller-ref=$ref" >> $GITHUB_OUTPUT