blank_issues_enabled: false
contact_links:
  - name: ADDON Jira project
    url: https://splunk.atlassian.net/jira/software/c/projects/ADDON/issues
    about: Create and track repository work in the authoritative ADDON project.
