name: AppInspect

description: >
  Performs validation checks on your Splunk app package against a set of standardized criteria to evaluate
  the app structure, features, security, and adherence to Splunk Cloud Platform requirements.
  Uses AppInspect API.

inputs:
  matrix_tags:
    required: true
  SPL_COM_USER:
    required: true
  SPL_COM_PASSWORD:
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: package-splunkbase
        path: build/package/

    - name: AppInspect API
      uses: splunk/appinspect-api-action@v3.0
      with:
        username: ${{ inputs.SPL_COM_USER }}
        password: ${{ inputs.SPL_COM_PASSWORD }}
        app_path: build/package/
        included_tags: ${{ inputs.matrix_tags }}

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: appinspect-api-html-report-${{ inputs.matrix_tags }}
        path: AppInspect_response.html