name: Test inventory

description: Detects number and version of test-types present in the addons tests folder

outputs:
  unit:
    value: ${{ steps.testset.outputs.unit }}
  knowledge:
    value: ${{ steps.testset.outputs.knowledge }}
  ui:
    value: ${{ steps.testset.outputs.ui }}
  modinput_functional:
    value: ${{ steps.testset.outputs.modinput_functional }}
  requirement_test:
    value: ${{ steps.testset.outputs.requirement_test }}
  scripted_inputs:
    value: ${{ steps.testset.outputs.scripted_inputs }}
  escu:
    value: ${{ steps.testset.outputs.escu }}
  ucc_modinput_functional:
    value: ${{ steps.modinput-version.outputs.ucc_modinput_tests }}

runs:
  using: composite
  steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check available test types
        id: testset
        shell: bash
        run: |
          find tests -type d -maxdepth 1 -mindepth 1 | sed 's|^tests/||g' |  while read -r TESTSET; do echo "$TESTSET=true" >> "$GITHUB_OUTPUT"; echo "$TESTSET::true"; done

      - name: Check modinput tests version
        id: modinput-version
        shell: bash
        run: |
          CENTAURS_MODINPUT_TESTS_CHECK_DIR="tests/modinput_functional/centaurs"
          ucc_modinput_tests="true"
          if [ -d "$CENTAURS_MODINPUT_TESTS_CHECK_DIR" ]; then
            ucc_modinput_tests="false"
          fi
          echo "ucc_modinput_tests=$ucc_modinput_tests" >> "$GITHUB_OUTPUT"
