name: Fossa test

description: >
  Checks report created in fossa-scan job. This action checks license compliance
  and vulnerabilities. The job uses .fossa.yml configuration file

inputs:
  FOSSA_API_KEY:
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run fossa test
      shell: bash
      run: |
        curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
        fossa test --debug
      env:
        FOSSA_API_KEY: ${{ inputs.FOSSA_API_KEY }}