name: Review secrets

description: > 
  Checks for addition/deletion of any secret/sensitive data in last 50 commits of the repository

runs:
  using: composite
  steps:
    - name: Checkout repository
      if: github.event_name != 'pull_request'
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: "0"

    - name: Checkout repo for PR
      if: github.event_name == 'pull_request'
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: "0"
        ref: ${{ github.head_ref }}
        
    - name: Trufflehog Actions Scan
      uses: edplato/trufflehog-actions-scan@v0.9l-beta
      with:
        scanArguments: "--max_dept 5 -x .github/workflows/exclude-patterns.txt --allow .github/workflows/trufflehog-false-positive.json"
