name: Fossa scan

description: >
  Analyzes third-party dependencies, generate a report, and upload
  the report as an artifact for further inspection or use.

inputs:
  FOSSA_API_KEY:
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run fossa anlysis and create report
      shell: bash
      run: |
        curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
        fossa analyze --debug
        fossa report attribution --format text --timeout 600 > /tmp/THIRDPARTY
      env:
        FOSSA_API_KEY: ${{ inputs.FOSSA_API_KEY }}

    - name: Upload THIRDPARTY file
      uses: actions/upload-artifact@v3
      with:
        name: THIRDPARTY
        path: /tmp/THIRDPARTY