name: Compliance copyrights

description: >
  Reuse compliance check. Analyze third-party dependencies, generate a report,
  and upload the report as an artifact for further inspection or use.

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1.1