name: lightweight-check

# this workflow utilises `dynamic-uses` action to be able to dynamically reference the version of Composite Actions used in the jobs
# this is to ensure that versions of particular actions are consistent with the version of the whole reusable workflow

on:
  workflow_call:
    secrets:
      GH_TOKEN_ADMIN:
        description: Github admin token
        required: true
      SA_GH_USER_NAME:
        description: GPG signature username
        required: true
      SA_GH_USER_EMAIL:
        description:  GPG signature user email
        required: true
      SA_GPG_PRIVATE_KEY:
        description: GPG signature private key
        required: true
      SA_GPG_PASSPHRASE:
        description: GPG signature passphrase
        required: true
      SEMGREP_PUBLISH_TOKEN:
        description: Semgrep token
        required: true
      AWS_ACCESS_KEY_ID:
        description: AWS access key id
        required: true
      AWS_DEFAULT_REGION:
        description: AWS default region
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: AWS secret access key
        required: true
      VT_API_KEY:
        description: Virustotal api key
        required: true
      SPL_COM_USER:
        description: username to splunk.com
        required: true
      SPL_COM_PASSWORD:
        description: password to splunk.com
        required: true
      FOSSA_API_KEY:
        description: API token for FOSSA app
        required: true

permissions:
  contents: read
  packages: read

concurrency:
  # allows for running this workflow simultaneously with main `resable-build-test-release.yml
  group:  ${{ github.head_ref || github.run_id }}-lightweight
  cancel-in-progress: true

jobs:
  get-called-ref:
    name: Get called ref
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.get-ref.outputs.caller-ref }}
    steps:
      - id: get-ref
        uses: splunk/addonfactory-workflow-addon-release/.github/actions/_called-wf-ref@fix/lightweight-workflow-ADDON-66448
        with: 
          GH_TOKEN_ADMIN: ${{ secrets.GH_TOKEN_ADMIN }}

  validate-pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    # inputs to `dynamic-uses` step
    env:
      GITHUB_TOKEN: ${{ github.token }}
    needs: get-called-ref
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: read
      packages: read
      pull-requests: read
      statuses: write
    steps:
      - uses: jenseng/dynamic-uses@v1
        with:
          uses: splunk/addonfactory-workflow-addon-release/.github/actions/validate-pr-title@${{ needs.get-called-ref.outputs.ref }}
          # inputs need to provided as a valid JSON string
          with: ${{ toJSON(env) }}

  meta:
    name: Prepare metadata
    runs-on: ubuntu-latest
    # inputs to `dynamic-uses` step
    env:
      SA_GH_USER_NAME: ${{ secrets.SA_GH_USER_NAME }}
      SA_GH_USER_EMAIL: ${{ secrets.SA_GH_USER_EMAIL }}
      SA_GPG_PRIVATE_KEY: ${{ secrets.SA_GPG_PRIVATE_KEY }}
      SA_GPG_PASSPHRASE: ${{ secrets.SA_GPG_PASSPHRASE }}
    outputs:
      # outputs from `dynamic-uses` action are passed as a JSON string
      sc4s: ${{ fromJSON(steps.meta.outputs.outputs).sc4s }}
    needs: get-called-ref
    steps:
      - uses: jenseng/dynamic-uses@v1
        id: meta
        with:
          uses: splunk/addonfactory-workflow-addon-release/.github/actions/meta@${{ needs.get-called-ref.outputs.ref }}
          # inputs need to provided as a valid JSON string
          with: ${{ toJSON(env) }}

  fossa-scan:
    name: FOSSA scan
    runs-on: ubuntu-latest
    # inputs to `dynamic-uses` step
    env:
      FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
    needs: get-called-ref
    steps:
      - uses: jenseng/dynamic-uses@v1
        with:
          uses: splunk/addonfactory-workflow-addon-release/.github/actions/fossa-scan@${{ needs.get-called-ref.outputs.ref }}
          # inputs need to provided as a valid JSON string
          with: ${{ toJSON(env) }}

  fossa-test:
    continue-on-error: true
    name: FOSSA test
    runs-on: ubuntu-latest
    # inputs to `dynamic-uses` step
    env:
      FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
    needs:
      - fossa-scan
      - get-called-ref
    steps:
      - uses: jenseng/dynamic-uses@v1
        with:
          uses: splunk/addonfactory-workflow-addon-release/.github/actions/fossa-test@${{ needs.get-called-ref.outputs.ref }}
          # inputs need to provided as a valid JSON string
          with: ${{ toJSON(env) }}

  compliance-copyrights:
    name: Compliance copyrights
    runs-on: ubuntu-latest
    needs: get-called-ref
    steps:
      - uses: jenseng/dynamic-uses@v1
        with:
          uses: splunk/addonfactory-workflow-addon-release/.github/actions/compliance-copyrights@${{ needs.get-called-ref.outputs.ref }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: get-called-ref
    steps:
      - uses: jenseng/dynamic-uses@v1
        with:
          uses: splunk/addonfactory-workflow-addon-release/.github/actions/lint@${{ needs.get-called-ref.outputs.ref }}

  review-secrets:
    name: Review secrets
    runs-on: ubuntu-latest
    needs: get-called-ref
    steps:
      - uses: jenseng/dynamic-uses@v1
        with:
          uses: splunk/addonfactory-workflow-addon-release/.github/actions/review-secrets@${{ needs.get-called-ref.outputs.ref }}

  semgrep:
    name: Semgrep security check
    runs-on: ubuntu-latest
    # inputs to `dynamic-uses` step
    env: 
      SEMGREP_PUBLISH_TOKEN: ${{ secrets.SEMGREP_PUBLISH_TOKEN }}
    needs: get-called-ref
    steps:
      - uses: jenseng/dynamic-uses@v1
        with:
          uses: splunk/addonfactory-workflow-addon-release/.github/actions/semgrep@${{ needs.get-called-ref.outputs.ref }}
          # inputs need to provided as a valid JSON string
          with:
            ${{ toJSON(env) }}

  test-inventory:
    name: Test inventory
    runs-on: ubuntu-latest
    # outputs from `dynamic-uses` action are passed as a JSON string
    outputs:
      unit: ${{ fromJSON(steps.test-inventory.outputs.outputs).unit }}
      ucc_modinput_functional: ${{ fromJSON(steps.test-inventory.outputs.outputs).ucc_modinput_functional }}
      modinput_functional: ${{ fromJSON(steps.test-inventory.outputs.outputs).modinput_functional }}
      requirement_test: ${{ fromJSON(steps.test-inventory.outputs.outputs).requirement_test }}
    needs: get-called-ref
    steps:
      - uses: jenseng/dynamic-uses@v1
        id: test-inventory
        with:
          uses: splunk/addonfactory-workflow-addon-release/.github/actions/test-inventory@${{ needs.get-called-ref.outputs.ref }}

  # Two separate unit test jobs needed as jobs that depend on unit-test success can't proceed
  # if any matrix job fails. Currently python 3.9 may fail as it's not supported in all TAs.
  # TODO: group these jobs into the matrix once python 3.9 is supported

  run-unit-tests-3_7:
    name: Unit tests 3.7
    if: ${{ needs.test-inventory.outputs.unit == 'true' }}
    runs-on: ubuntu-latest
    # inputs to `dynamic-uses` step
    env:
      python_version: 3.7
      GH_TOKEN_ADMIN: ${{ secrets.GH_TOKEN_ADMIN }}
    needs:
      - test-inventory
      - get-called-ref
    permissions: 
      actions: read
      deployments: read
      contents: read
      packages: read
      statuses: read
      checks: write
    steps:
      - uses: jenseng/dynamic-uses@v1
        with:
          uses: splunk/addonfactory-workflow-addon-release/.github/actions/unit-tests@${{ needs.get-called-ref.outputs.ref }}
          # inputs need to provided as a valid JSON string
          with: ${{ toJSON(env) }}

  run-unit-tests-3_9:
    name: Unit tests 3.9
    if: ${{ needs.test-inventory.outputs.unit == 'true' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    # inputs to `dynamic-uses` step
    env:
      python_version: 3.7
      GH_TOKEN_ADMIN: ${{ secrets.GH_TOKEN_ADMIN }}
    needs:
      - test-inventory
      - get-called-ref
    permissions: 
      actions: read
      deployments: read
      contents: read
      packages: read
      statuses: read
      checks: write
    steps:
      - uses: jenseng/dynamic-uses@v1
        with:
          uses: splunk/addonfactory-workflow-addon-release/.github/actions/unit-tests@${{ needs.get-called-ref.outputs.ref }}
          # inputs need to provided as a valid JSON string
          with: ${{ toJSON(env) }}

  build:
    name: Build python-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    needs:
      - test-inventory
      - meta
      - compliance-copyrights
      - lint
      - review-secrets
      - semgrep
      - run-unit-tests-3_7
      - get-called-ref
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.9"
    if: ${{ !cancelled() && (needs.run-unit-tests-3_7.result == 'success' || needs.run-unit-tests-3_7.result == 'skipped') }}
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Very Important: semantic-release won't trigger a tagged
          # build if this is not set to false
          persist-credentials: false
      - name: Checkout repository
        uses: jenseng/dynamic-uses@v1
        env:
          repositories: splunk/addonfactory-workflow-addon-release@${{ needs.get-called-ref.outputs.ref }}
        with:
          uses: vweevers/multi-checkout-action@v1
          with: ${{ toJSON(env) }}
      - name: Run build
        uses: ./../splunk/addonfactory-workflow-addon-release/.github/actions/build
        with:
          python_version: ${{ matrix.python-version }}
          SA_GH_USER_NAME: ${{ secrets.SA_GH_USER_NAME }}
          SA_GH_USER_EMAIL: ${{ secrets.SA_GH_USER_EMAIL }}
          SA_GPG_PRIVATE_KEY: ${{ secrets.SA_GPG_PRIVATE_KEY }}
          SA_GPG_PASSPHRASE: ${{ secrets.SA_GPG_PASSPHRASE }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ucc_modinput_functional: ${{ needs.test-inventory.outputs.ucc_modinput_functional}}
          modinput_functional: ${{ needs.test-inventory.outputs.modinput_functional}}

  virustotal:
    runs-on: ubuntu-latest
    # inputs to `dynamic-uses` step
    env:
      VT_API_KEY: ${{ secrets.VT_API_KEY }}
    needs:
      - build
      - get-called-ref
    if: ${{ !cancelled() && needs.build.result == 'success' }}
    steps:
      - uses: jenseng/dynamic-uses@v1
        with:
          uses: splunk/addonfactory-workflow-addon-release/.github/actions/virustotal@${{ needs.get-called-ref.outputs.ref }}
          # inputs need to provided as a valid JSON string
          with: ${{ toJSON(env) }}

  run-requirements-unit-tests:
    name: Requirements unit tests
    runs-on: ubuntu-latest
    # inputs to `dynamic-uses` step
    needs:
      - build
      - test-inventory
      - get-called-ref
    if: ${{ !cancelled() && needs.build.result == 'success' && needs.test-inventory.outputs.requirement_test == 'true' }}
    permissions: 
      actions: read
      deployments: read
      contents: read
      packages: read
      statuses: read
      checks: write
    steps:
      - uses: jenseng/dynamic-uses@v1
        with:
          uses: splunk/addonfactory-workflow-addon-release/.github/actions/requirements-unit-tests@${{ needs.get-called-ref.outputs.ref }}

  appinspect-cli:
    name: AppInspect CLI ${{ matrix.tags }}
    runs-on: ubuntu-latest
    # inputs to `dynamic-uses` step
    env:
      matrix_tags: ${{ matrix.tags }}
    needs:
      - build
      - get-called-ref
    if: ${{ !cancelled() && needs.build.result == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        tags:
          - "cloud"
          - "appapproval"
          - "deprecated_feature"
          - "developer_guidance"
          - "future"
          - "self-service"
          - "splunk_appinspect"
          - "manual"
    steps:
      - uses: jenseng/dynamic-uses@v1
        with:
          uses: splunk/addonfactory-workflow-addon-release/.github/actions/appinspect-cli@${{ needs.get-called-ref.outputs.ref }}
          # inputs need to provided as a valid JSON string
          with: ${{ toJSON(env) }}

  artifact-registry:
    name: Artifact registry
    runs-on: ubuntu-latest
    # inputs to `dynamic-uses` step
    env:
      sc4s: ${{ needs.meta.outputs.sc4s }}
    needs:
      - virustotal
      - meta
      - get-called-ref
    if: ${{ !cancelled() && needs.virustotal.result == 'success' && needs.meta.result == 'success' }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: jenseng/dynamic-uses@v1
        with:
          uses: splunk/addonfactory-workflow-addon-release/.github/actions/artifact-registry@${{ needs.get-called-ref.outputs.ref }}
          # inputs need to provided as a valid JSON string
          with: ${{ toJSON(env) }}
