name: test-split 
on:
  workflow_call:
    inputs: 
      matrixvalues:
        description: 'Stringified JSON object listing target Node versions'
        default: '15.x'
        required: false
        type: string
      marker_list:
        description: 'marker list'
        default: "''"
        required: false
        type: string
      test-timeout:
        required: false
        type: number
        default: 120
      marker_string:
        required: false
        type: string
        default: ''
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      test-arg-first: ${{ steps.create-test-arg-first.outputs.test-arg-first }}
    steps:
      - name: create test argument first
        id: create-test-arg-first
        shell: bash
        run: |
          if [ -z "${{ inputs.marker_list }}" ]
          then
            TEST_ARG="-m ''"
          else
            TEST_ARG="-m ${{ inputs.marker_list }}"         
          fi
          echo "::set-output name=test-arg-first::$TEST_ARG"
  
  run-mod-inputs:
    needs:
      - setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix: 
        splitvalues: ${{fromJson(inputs.matrixvalues)}}
        marker_list: ${{fromJson(inputs.marker_list)}}
        #marker_list: ${{ needs.setup.outputs.test-arg-first }}
        test-timeout:
        - ${{ inputs.test-timeout }}
       # marker_string: 
       # - ${{fromJson(inputs.marker_string)}}
    steps:
      - name: create test argument
        id: create-test-arg
        shell: bash
        run: |
          if [ -z "${{ inputs.marker_list }}" ]
          then
            TEST_ARG=""
          else
            TEST_ARG="-m ${{ inputs.marker_list }}"         
          fi
          echo "::set-output name=test-arg::$TEST_ARG"
      - run: echo "hello"
        shell: bash
      - run: echo ${{ matrix.splitvalues }}
        shell: bash
      - run: echo ${{ matrix.marker_list }}
        shell: bash
      - run: echo ${{ needs.setup.outputs.test-arg-first }}
        shell: bash
#       - run: echo ${{ steps.create-test-arg.outputs.test-arg }}
#         shell: bash
        
