name: test-split 
on:
  workflow_call:
    inputs: 
      matrixvalues:
        description: 'Stringified JSON object listing target Node versions'
        default: '15.x'
        required: false
        type: string
      marker_list:
        description: 'marker list'
        default: ''
        required: false
        type: string
      test-timeout:
        required: false
        type: number
        default: 120
      marker_string:
        required: false
        type: string
        default: ''
jobs:
  run-mod-inputs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix: 
        splitvalues: ${{fromJson(inputs.matrixvalues)}}
        marker_List: ${{fromJson(inputs.marker_list)}}
        test-timeout:
        - ${{ inputs.test-timeout }}
        #marker_String: 
        #- ${{fromJson(inputs.marker_string)}}
    steps:
      - name: create test argument
        id: create-test-arg
        shell: bash
        run: |
          if [ -z "${{ inputs.marker_string }}" ]
          then
            TEST_ARG=""
          else
            TEST_ARG="-m ${{ inputs.marker_string }}"         
          fi
          echo "::set-output name=test-arg::$TEST_ARG"
      - run: echo "hello"
        shell: bash
      - run: echo ${{ matrix.splitvalues }}
        shell: bash
      - run: echo ${{ steps.create-test-arg.outputs.test-arg }}
        shell: bash
        
